name: PlayTimeTracker
main: cat.nyaa.playtimetracker.PTT
version: ${version}
depend: [NyaaCore]
softdepend: [Essentials]
api-version: 1.13

commands:
  playtimetracker:
    description: Main command for PlayTimeTracker
    aliases: ptt
    permission: ptt.view
    permission-message: You do not have permission node <permission>
    usage: "/<command> [{PlayerName}|reset <{PlayerName}|all>|reload|acquire|ac|recur <PlayerName> <RuleName>|help]"

permissions:
  ptt.view:
    description: Basic command permission
    default: true
  ptt.acquire:
    description: Redeem the reward related to the rule
    default: true
  ptt.view.others:
    description: See other player's statistic
    default: op
  ptt.reset:
    description: Reset statistic for some players
    default: op
  ptt.reload:
    description: Reload configure
    default: op
  ptt.recurrence:
    description: Set recurrence rule
    default: op
