package cat.nyaa.playtimetracker.db.model;

import cat.nyaa.nyaacore.orm.annotations.Column;
import cat.nyaa.nyaacore.orm.annotations.Table;

import java.util.Objects;
import java.util.UUID;

@Table("time")
public class TimeTrackerDbModel {

    @Column(name = "player", primary = true)
    public UUID playerUniqueId;
    @Column(name = "lastUpdate")
    public long lastUpdate; // last update unix timestamp millisecond
    @Column(name = "dailyTime")
    public long dailyTime; // millisecond
    @Column(name = "weeklyTime")
    public long weeklyTime; // millisecond
    @Column(name = "monthlyTime")
    public long monthlyTime; // millisecond
    @Column(name = "totalTime")
    public long totalTime; // millisecond
    @Column(name = "lastSeen")
    public long lastSeen; // last logout unix timestamp millisecond

    public TimeTrackerDbModel(UUID playerUniqueId, long lastUpdate, long dailyTime, long weeklyTime, long monthlyTime, long totalTime, long lastSeen) {
        this.playerUniqueId = playerUniqueId;
        this.lastUpdate = lastUpdate;
        this.dailyTime = dailyTime;
        this.weeklyTime = weeklyTime;
        this.monthlyTime = monthlyTime;
        this.totalTime = totalTime;
        this.lastSeen = lastSeen;
    }


    public TimeTrackerDbModel() {

    }


    public UUID getPlayerUniqueId() {
        return playerUniqueId;
    }

    public void setPlayerUniqueId(UUID playerUniqueId) {
        this.playerUniqueId = playerUniqueId;
    }

    public long getLastUpdate() {
        return lastUpdate;
    }

    public void setLastUpdate(long lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    public long getDailyTime() {
        return dailyTime;
    }

    public void setDailyTime(long dailyTime) {
        this.dailyTime = dailyTime;
    }

    public void addDailyTime(long dailyTime) {
        this.dailyTime += dailyTime;
    }

    public long getWeeklyTime() {
        return weeklyTime;
    }

    public void setWeeklyTime(long weeklyTime) {
        this.weeklyTime = weeklyTime;
    }

    public void addWeeklyTime(long weeklyTime) {
        this.weeklyTime += weeklyTime;
    }

    public long getMonthlyTime() {
        return monthlyTime;
    }

    public void setMonthlyTime(long monthlyTime) {
        this.monthlyTime = monthlyTime;
    }

    public void addMonthlyTime(long monthlyTime) {
        this.monthlyTime += monthlyTime;
    }

    public long getTotalTime() {
        return totalTime;
    }

    public void setTotalTime(long totalTime) {
        this.totalTime = totalTime;
    }

    public void addTotalTime(long totalTime) {
        this.totalTime += totalTime;
    }

    public long getLastSeen() {
        return lastSeen;
    }

    public void setLastSeen(long lastSeen) {
        this.lastSeen = lastSeen;
    }

    // generated by IntelliJ IDEA
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof TimeTrackerDbModel that)) return false;
        if (!Objects.equals(playerUniqueId, that.playerUniqueId)) return false;
        if (lastUpdate != that.lastUpdate) return false;
        if (dailyTime != that.dailyTime) return false;
        if (weeklyTime != that.weeklyTime) return false;
        if (monthlyTime != that.monthlyTime) return false;
        if (totalTime != that.totalTime) return false;
        return lastSeen == that.lastSeen;
    }

    // generated by IntelliJ IDEA
    @Override
    public int hashCode() {
        int result = playerUniqueId != null ? playerUniqueId.hashCode() : 0;
        result = 31 * result + (int) (lastUpdate ^ (lastUpdate >>> 32));
        result = 31 * result + (int) (dailyTime ^ (dailyTime >>> 32));
        result = 31 * result + (int) (weeklyTime ^ (weeklyTime >>> 32));
        result = 31 * result + (int) (monthlyTime ^ (monthlyTime >>> 32));
        result = 31 * result + (int) (totalTime ^ (totalTime >>> 32));
        result = 31 * result + (int) (lastSeen ^ (lastSeen >>> 32));
        return result;
    }
}
